### ISSUE TITLE
Translations NL-EN-FR

### ISSUE THREAD

**Issue by BramBleys** [oSoc19/bebudget#8]
- Maybe add a config variable and change it when clicking the language in the top right. 
- Keep one file with all translation per language and structure them like: home_title: "Do you know where your taxes are going?" and for NL: home_title: "Weet jij waar je belastingen heen gaan?"

**Comment by BramBleys** [comment]
Add dropdown in upload form

**Comment by EmmyBruynseels** [comment]
done in translations branch
